port 1194
proto udp
dev tun
tun-mtu 1420
ca keys/ca.crt
cert keys/server.crt
key keys/server.key
dh keys/dh.pem
auth SHA256
tls-auth keys/ta.key 0
server 192.168.50.0 255.255.255.0
push "redirect-gateway def1 bypass-dhcp"
keepalive 10 120
cipher AES-256-GCM
user nobody
group nogroup
persist-key
persist-tun
status /var/log/openvpn-status.log
log /var/log/openvpn-server.log
verb 3
topology subnet
