BRIDGE_NET="192.168.56."
BOX_NAME_UBUNTU = "bento-ubuntu-24.04-amd64"
BOX_URL_UBUNTU = "file://~/study/codeby_devops/" + BOX_NAME_UBUNTU + ".box"
BOX_NAME_ROCKYLINUX = "bento-rockylinux-9-amd64"
BOX_URL_ROCKYLINUX = "file://~/study/codeby_devops/" + BOX_NAME_ROCKYLINUX + ".box"

MACHINES = {
  "l13ubu" => {
    :box_name => BOX_NAME_UBUNTU,
    :box_url => BOX_URL_UBUNTU,
    :host_name => "l13-ubuntu",  
    :ip_addr => BRIDGE_NET + "110",
    :check_update => false,
    :cpu => 1,
    :ram => 1024,
    :gui => false,
  },
  "l13rocky" => {
    :box_name => BOX_NAME_ROCKYLINUX,
    :box_url => BOX_URL_ROCKYLINUX,
    :host_name => "l13-rockylinux",  
    :ip_addr => BRIDGE_NET + "111",
    :check_update => false,
    :cpu => 1,
    :ram => 1024,
    :gui => false,
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_url = boxconfig[:box_url]
      box.vm.hostname = boxconfig[:host_name]
      box.vm.box_check_update = boxconfig[:check_update]
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider :virtualbox do |vb|
        vb.name = boxconfig[:host_name]
        vb.cpus = boxconfig[:cpu]
        vb.memory = boxconfig[:ram]
        vb.gui = boxconfig[:gui]
      end
      if (!boxconfig[:shpath].nil?)
        box.vm.provision "shell", path: boxconfig[:shpath]
      end
    end
  end
end
