namespace: dev


storageClass:
  name: local-storage


mysql:
  replicas: 1
  image: mysql:8.0
  service:
    port: 3306
  db:
    host: mysql
    name: wordpress
    user: wpuser
    pass: wppass
    rootpass: rootpass

  storage: 1Gi
  localPath: /data/mysql

  node: kind-worker


wordpress:
  replicas: 1
  image: wordpress:latest
  resources: {
    "requests": {
      "cpu": "100m",
      "memory": "128Mi"
    },
    "limits": {
      "cpu": "500m",
      "memory": "512Mi"
    }
  }

  storage: 1Gi
  localPath: /data/wordpress

  node: kind-worker2

  service:
    type: NodePort
    port: 80
    nodePort: 30080

  hpa:
    minReplicas: 1
    maxReplicas: 1
    targetCpuUtilization: 70
