apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: {{ .Values.namespace }}
data:
  MYSQL_DATABASE: {{ .Values.mysql.db.name | quote }}
  MYSQL_USER: {{ .Values.mysql.db.user | quote }}
