apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.db.rootpass }}
  MYSQL_PASSWORD: {{ .Values.mysql.db.pass }}
