apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.wordpress.service.type }}
  selector:
    app: wordpress
  ports:
    - name: wordpress
      protocol: TCP
      port: {{ .Values.wordpress.service.port }}
      targetPort: 80
      {{- if eq .Values.wordpress.service.type "NodePort" }}
      nodePort: {{ .Values.wordpress.service.nodePort }}
      {{- end }}
