apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: {{ .Values.wordpress.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass.name }}
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ .Values.wordpress.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - {{ .Values.wordpress.node }}
