lessonN: "lesson13"
apache_pkg: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' if ansible_os_family == 'RedHat' }}"

apache_owner: "{{ 'www-data' if ansible_os_family == 'Debian' else 'apache' if ansible_os_family == 'RedHat' }}"
apache_group: "{{ 'www-data' if ansible_os_family == 'Debian' else 'apache' if ansible_os_family == 'RedHat' }}"

apache_cfg_default: "000-default.conf"
apache_cfg: "{{lessonN}}.conf"
apache_cfg_dir: "{{ '/etc/apache2/sites-available' if ansible_os_family == 'Debian' else '/etc/httpd/conf.d' if ansible_os_family == 'RedHat'}}"
apache_www: "/opt/apache2/www/{{lessonN}}.local/"
