BRIDGE_NET="192.168.56."
BOX_NAME = "bento-ubuntu-24.04-amd64"
MACHINES = {
  :sr => {
    :host_name => "server",  
    :ip_addr => BRIDGE_NET + "101",
    :check_update => false,
    :cpu => 1,
    :ram => 1024,
    :gui => false
  },
  :cl => {
    :host_name => "client",  
    :ip_addr => BRIDGE_NET + "102",
    :check_update => false,
    :cpu => 1,
    :ram => 1024,
    :gui => false
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = BOX_NAME
      box.vm.hostname = boxconfig[:host_name]
      box.vm.box_check_update = boxconfig[:check_update]
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider 'virtualbox' do |vb|
        vb.name = boxconfig[:host_name]
        vb.cpus = boxconfig[:cpu]
        vb.memory = boxconfig[:ram]
        vb.gui = boxconfig[:gui]
      end
      if "#{boxname}" == 'cl'
        box.vm.provision "shell", path: "scripts/ssh_cltosr.sh"
      end
    end
  end
end
